//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bomberman {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bomberman.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] balloom_dead {
            get {
                object obj = ResourceManager.GetObject("balloom_dead", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] balloom_left1 {
            get {
                object obj = ResourceManager.GetObject("balloom_left1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] balloom_left2 {
            get {
                object obj = ResourceManager.GetObject("balloom_left2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] balloom_left3 {
            get {
                object obj = ResourceManager.GetObject("balloom_left3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] balloom_right1 {
            get {
                object obj = ResourceManager.GetObject("balloom_right1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] balloom_right2 {
            get {
                object obj = ResourceManager.GetObject("balloom_right2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] balloom_right3 {
            get {
                object obj = ResourceManager.GetObject("balloom_right3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bomb {
            get {
                object obj = ResourceManager.GetObject("bomb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bomb_1 {
            get {
                object obj = ResourceManager.GetObject("bomb_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bomb_2 {
            get {
                object obj = ResourceManager.GetObject("bomb_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bomb_exploded {
            get {
                object obj = ResourceManager.GetObject("bomb_exploded", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bomb_exploded1 {
            get {
                object obj = ResourceManager.GetObject("bomb_exploded1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bomb_exploded2 {
            get {
                object obj = ResourceManager.GetObject("bomb_exploded2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] brick {
            get {
                object obj = ResourceManager.GetObject("brick", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] brick_exploded {
            get {
                object obj = ResourceManager.GetObject("brick_exploded", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] brick_exploded1 {
            get {
                object obj = ResourceManager.GetObject("brick_exploded1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] brick_exploded2 {
            get {
                object obj = ResourceManager.GetObject("brick_exploded2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] doll_dead {
            get {
                object obj = ResourceManager.GetObject("doll_dead", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] doll_left1 {
            get {
                object obj = ResourceManager.GetObject("doll_left1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] doll_left2 {
            get {
                object obj = ResourceManager.GetObject("doll_left2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] doll_left3 {
            get {
                object obj = ResourceManager.GetObject("doll_left3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] doll_right1 {
            get {
                object obj = ResourceManager.GetObject("doll_right1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] doll_right2 {
            get {
                object obj = ResourceManager.GetObject("doll_right2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] doll_right3 {
            get {
                object obj = ResourceManager.GetObject("doll_right3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_horizontal {
            get {
                object obj = ResourceManager.GetObject("explosion_horizontal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_horizontal_left_last {
            get {
                object obj = ResourceManager.GetObject("explosion_horizontal_left_last", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_horizontal_left_last1 {
            get {
                object obj = ResourceManager.GetObject("explosion_horizontal_left_last1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_horizontal_left_last2 {
            get {
                object obj = ResourceManager.GetObject("explosion_horizontal_left_last2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_horizontal_right_last {
            get {
                object obj = ResourceManager.GetObject("explosion_horizontal_right_last", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_horizontal_right_last1 {
            get {
                object obj = ResourceManager.GetObject("explosion_horizontal_right_last1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_horizontal_right_last2 {
            get {
                object obj = ResourceManager.GetObject("explosion_horizontal_right_last2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_horizontal1 {
            get {
                object obj = ResourceManager.GetObject("explosion_horizontal1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_horizontal2 {
            get {
                object obj = ResourceManager.GetObject("explosion_horizontal2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_vertical {
            get {
                object obj = ResourceManager.GetObject("explosion_vertical", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_vertical_down_last {
            get {
                object obj = ResourceManager.GetObject("explosion_vertical_down_last", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_vertical_down_last1 {
            get {
                object obj = ResourceManager.GetObject("explosion_vertical_down_last1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_vertical_down_last2 {
            get {
                object obj = ResourceManager.GetObject("explosion_vertical_down_last2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_vertical_top_last {
            get {
                object obj = ResourceManager.GetObject("explosion_vertical_top_last", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_vertical_top_last1 {
            get {
                object obj = ResourceManager.GetObject("explosion_vertical_top_last1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_vertical_top_last2 {
            get {
                object obj = ResourceManager.GetObject("explosion_vertical_top_last2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_vertical1 {
            get {
                object obj = ResourceManager.GetObject("explosion_vertical1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] explosion_vertical2 {
            get {
                object obj = ResourceManager.GetObject("explosion_vertical2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] grass {
            get {
                object obj = ResourceManager.GetObject("grass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] kondoria_dead {
            get {
                object obj = ResourceManager.GetObject("kondoria_dead", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] kondoria_left1 {
            get {
                object obj = ResourceManager.GetObject("kondoria_left1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] kondoria_left2 {
            get {
                object obj = ResourceManager.GetObject("kondoria_left2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] kondoria_left3 {
            get {
                object obj = ResourceManager.GetObject("kondoria_left3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] kondoria_right1 {
            get {
                object obj = ResourceManager.GetObject("kondoria_right1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] kondoria_right2 {
            get {
                object obj = ResourceManager.GetObject("kondoria_right2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] kondoria_right3 {
            get {
                object obj = ResourceManager.GetObject("kondoria_right3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###############################
        ///#                             #
        ///# # # # # # # # # # # # # # # #
        ///#                             #
        ///# # # # # # # # # # # # # # # #
        ///#                             #
        ///# # # # # # # # # # # # # # # #
        ///#                             #
        ///# # # # # # # # # # # # # # # #
        ///#                             #
        ///# # # # # # # # # # # # # # # #
        ///#                             #
        ///###############################
        ///.
        /// </summary>
        public static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] minvo_dead {
            get {
                object obj = ResourceManager.GetObject("minvo_dead", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] minvo_left1 {
            get {
                object obj = ResourceManager.GetObject("minvo_left1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] minvo_left2 {
            get {
                object obj = ResourceManager.GetObject("minvo_left2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] minvo_left3 {
            get {
                object obj = ResourceManager.GetObject("minvo_left3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] minvo_right1 {
            get {
                object obj = ResourceManager.GetObject("minvo_right1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] minvo_right2 {
            get {
                object obj = ResourceManager.GetObject("minvo_right2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] minvo_right3 {
            get {
                object obj = ResourceManager.GetObject("minvo_right3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] mob_dead1 {
            get {
                object obj = ResourceManager.GetObject("mob_dead1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] mob_dead2 {
            get {
                object obj = ResourceManager.GetObject("mob_dead2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] mob_dead3 {
            get {
                object obj = ResourceManager.GetObject("mob_dead3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] oneal_dead {
            get {
                object obj = ResourceManager.GetObject("oneal_dead", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] oneal_left1 {
            get {
                object obj = ResourceManager.GetObject("oneal_left1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] oneal_left2 {
            get {
                object obj = ResourceManager.GetObject("oneal_left2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] oneal_left3 {
            get {
                object obj = ResourceManager.GetObject("oneal_left3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] oneal_right1 {
            get {
                object obj = ResourceManager.GetObject("oneal_right1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] oneal_right2 {
            get {
                object obj = ResourceManager.GetObject("oneal_right2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] oneal_right3 {
            get {
                object obj = ResourceManager.GetObject("oneal_right3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_dead1 {
            get {
                object obj = ResourceManager.GetObject("player_dead1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_dead2 {
            get {
                object obj = ResourceManager.GetObject("player_dead2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_dead3 {
            get {
                object obj = ResourceManager.GetObject("player_dead3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_down {
            get {
                object obj = ResourceManager.GetObject("player_down", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_down1 {
            get {
                object obj = ResourceManager.GetObject("player_down1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_down2 {
            get {
                object obj = ResourceManager.GetObject("player_down2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_left {
            get {
                object obj = ResourceManager.GetObject("player_left", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_left1 {
            get {
                object obj = ResourceManager.GetObject("player_left1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_left2 {
            get {
                object obj = ResourceManager.GetObject("player_left2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_right {
            get {
                object obj = ResourceManager.GetObject("player_right", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_right1 {
            get {
                object obj = ResourceManager.GetObject("player_right1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_right2 {
            get {
                object obj = ResourceManager.GetObject("player_right2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_up {
            get {
                object obj = ResourceManager.GetObject("player_up", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_up1 {
            get {
                object obj = ResourceManager.GetObject("player_up1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_up2 {
            get {
                object obj = ResourceManager.GetObject("player_up2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] portal {
            get {
                object obj = ResourceManager.GetObject("portal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] powerup_bombpass {
            get {
                object obj = ResourceManager.GetObject("powerup_bombpass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] powerup_bombs {
            get {
                object obj = ResourceManager.GetObject("powerup_bombs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] powerup_detonator {
            get {
                object obj = ResourceManager.GetObject("powerup_detonator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] powerup_flamepass {
            get {
                object obj = ResourceManager.GetObject("powerup_flamepass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] powerup_flames {
            get {
                object obj = ResourceManager.GetObject("powerup_flames", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] powerup_speed {
            get {
                object obj = ResourceManager.GetObject("powerup_speed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] powerup_wallpass {
            get {
                object obj = ResourceManager.GetObject("powerup_wallpass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] wall {
            get {
                object obj = ResourceManager.GetObject("wall", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
