//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bomberman {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bomberman.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###############################
        ///#                             #
        ///# # # # # # # # # # # # # # # #
        ///#                             #
        ///# # # # # # # # # # # # # # # #
        ///#                             #
        ///# # # # # # # # # # # # # # # #
        ///#                             #
        ///# # # # # # # # # # # # # # # #
        ///#                             #
        ///# # # # # # # # # # # # # # # #
        ///#                             #
        ///###############################
        ///.
        /// </summary>
        public static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###############################
        ///#p * *r       *  ** * *      *#
        ///# # # # #*# # #*# # # # # #*# #
        ///#    * * *** **      *    **  #
        ///# #*# # # # #s# #b#s# # # # #*#
        ///#          K     **      *  R*#
        ///# # #*# # # # # #*#*#*#*# # # #
        ///#   *        *   * *D* *  N   #
        ///# # # # #*# # # # # # #*# #*# #
        ///#   ****         *s           #
        ///# # # # # # # # # #*# # # # #*#
        ///#  ** *   *    r              #
        ///###############################.
        /// </summary>
        public static string stage1 {
            get {
                return ResourceManager.GetString("stage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###############################
        ///#p    * **    *   r   r       #
        ///# # # #*# # # # # # # # # # # #
        ///#      ** N *  *   * ** r *   #
        ///# # # # # #*# # # # # # #*# # #
        ///#*   * K    *b* *   **        #
        ///# # # # # # # # # # # # # #*# #
        ///#    *     *        *    **  r#
        ///# #*# # #*#*#*#*# # #1# # #*# #
        ///#        * r *r*    *   R     #
        ///#*# # # # # # # # # # #*# # #*#
        ///#**    * **    ** **D     s   #
        ///###############################.
        /// </summary>
        public static string stage2 {
            get {
                return ResourceManager.GetString("stage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###############################
        ///#p    * **    *   r   r       #
        ///# # # #*# # # # # # # # # # # #
        ///#      ** N *  *   * ** r *   #
        ///# # # # # #*#*# # # # # #*# # #
        ///#*   * K    *b* *   **        #
        ///# # # # # # #*# # # # # # #*# #
        ///#    *     *        *    **  r#
        ///# #*# # #*#*#*#*# # #1# # #*# #
        ///#        * r *r*    *   R     #
        ///#*# # # # # # # # # # #*# # #*#
        ///#**    * **    ** **D     s   #
        ///###############################.
        /// </summary>
        public static string stage3 {
            get {
                return ResourceManager.GetString("stage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###############################
        ///#p    * **    *   r   r       #
        ///# # # #*# # # # # # # # # # # #
        ///#      ** N *  *   * ** r *   #
        ///# # # # # #*#*# # # # # #*# # #
        ///#*   * K    *b* *   **        #
        ///# # # # # # #*# # # # # # #*# #
        ///#    *     *        *    **  r#
        ///# #*# # #*#*#*#*# # #1# # #*# #
        ///#        * r *r*    *   R     #
        ///#*# # # # # # # # # # #*# # #*#
        ///#**    * **    ** **D     s   #
        ///###############################.
        /// </summary>
        public static string stage31 {
            get {
                return ResourceManager.GetString("stage31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###############################
        ///#p    * **    *   r   r       #
        ///# # # #*# # # # # # # # # # # #
        ///#      ** N *  *   * ** r *   #
        ///# # # # # #*#*# # # # # #*# # #
        ///#*   * K    *b* *   **        #
        ///# # # # # # #*# # # # # # #*# #
        ///#    *     *        *    **  r#
        ///# #*# # #*#*#*#*# # #1# # #*# #
        ///#        * r *r*    *   R     #
        ///#*# # # # # # # # # # #*# # #*#
        ///#**    * **    ** **D     s   #
        ///###############################.
        /// </summary>
        public static string stage4 {
            get {
                return ResourceManager.GetString("stage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###############################
        ///#p    * **    *   r   r       #
        ///# # # #*# # # # # # # # # # # #
        ///#      ** N *  *   * ** r *   #
        ///# # # # # #*#*# # # # # #*# # #
        ///#*   * K    *b* *   **        #
        ///# # # # # # #*# # # # # # #*# #
        ///#    *     *        *    **  r#
        ///# #*# # #*#*#*#*# # #1# # #*# #
        ///#        * r *r*    *   R     #
        ///#*# # # # # # # # # # #*# # #*#
        ///#**    * **    ** **D     s   #
        ///###############################.
        /// </summary>
        public static string stage41 {
            get {
                return ResourceManager.GetString("stage41", resourceCulture);
            }
        }
    }
}
